export enum E_RENDERING_CONTEXT_ID {
  DIMENSIONAL2 = '2d',
  WEBGL = 'webgl',
};

export enum E_DIMENSIONAL_ID {
  DIMENSIONAL2 = E_RENDERING_CONTEXT_ID.DIMENSIONAL2,
  DIMENSIONAL3 = E_RENDERING_CONTEXT_ID.WEBGL,
};